# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_letter', '0006_auto_20180203_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
